# Generated by Django 5.0.1 on 2024-01-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
