# Generated by Django 4.2.6 on 2023-11-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0002_alter_category_description_emlak'),
    ]

    operations = [
        migrations.AddField(
            model_name='emlak',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('emlak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emlak.emlak')),
            ],
        ),
    ]
